/* Generated By:JavaCC: Do not edit this line. SQLXMLParserTreeConstants.java Version 5.0 */
package de.upb.s2cx.parser;

public interface SQLXMLParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTSELECT = 1;
  public int JJTTABLE = 2;
  public int JJTCOLUMN = 3;
  public int JJTADDITIVETERM = 4;
  public int JJTTERM = 5;
  public int JJTFACTOR = 6;
  public int JJTWHERECLAUSE = 7;
  public int JJTGROUPBYCLAUSE = 8;
  public int JJTORDERBYCLAUSE = 9;
  public int JJTCONDITIONS = 10;
  public int JJTANDCONDITION = 11;
  public int JJTCONDITION = 12;
  public int JJTVALUECONDITION = 13;
  public int JJTEXISTSCONDITION = 14;
  public int JJTCOLUMNCONDITION = 15;
  public int JJTINCONDITION = 16;
  public int JJTLIKECONDITION = 17;
  public int JJTRELATIONALOPERATOR = 18;
  public int JJTXMLELEMENT = 19;
  public int JJTXMLATTRIBUTES = 20;
  public int JJTXMLATTRIBUTE = 21;
  public int JJTXMLCONCAT = 22;
  public int JJTXMLFOREST = 23;
  public int JJTXMLFORESTELEMENT = 24;
  public int JJTXMLAGG = 25;
  public int JJTSQLFUNCTION = 26;
  public int JJTVALUE = 27;
  public int JJTARRAY = 28;
  public int JJTXMLVALUE = 29;


  public String[] jjtNodeName = {
    "root",
    "select",
    "table",
    "column",
    "additiveTerm",
    "term",
    "factor",
    "whereClause",
    "groupByClause",
    "orderByClause",
    "conditions",
    "andCondition",
    "condition",
    "valueCondition",
    "existsCondition",
    "columnCondition",
    "inCondition",
    "likeCondition",
    "relationalOperator",
    "xmlElement",
    "xmlAttributes",
    "xmlAttribute",
    "xmlConcat",
    "xmlForest",
    "xmlForestElement",
    "xmlAgg",
    "sqlFunction",
    "value",
    "array",
    "xmlValue",
  };
}
/* JavaCC - OriginalChecksum=aa6b33449b549b04dbbc4c3e929fb090 (do not edit this line) */
